# Generated by Django 4.2.20 on 2025-05-02 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_title', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('slider_image', models.ImageField(blank=True, null=True, upload_to='slider_images/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('button_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sliders', to='blog.blogpost')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_images/'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='AccordionItem',
        ),
    ]
